### ISSUE TITLE
refine the syntax of object schema 

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4451]
The new schema is:
````
!!python/dict
  node:
    obj_type: :{{ 'group' if 'T{nodegroup.groupname}' == 'V{node}' else 'node' }}
    obj_info:
      groups: :{{ 'T{nodelist.groups}' if 'V{obj_type}' == 'node' else None }}
      grouptype: {{ 'T{nodegroup.grouptype}' if 'V{obj_type}' == 'group' else None }}
      members: {{ 'T{nodegroup.members}' if 'V{obj_type}' == 'group' else None }}
      filter: {{ 'T{nodegroup.wherevals}' if 'V{obj_type}' == 'group' else None }}
    device_type: {{ 'switch' if 'T{switches.switch}' == 'V{node}' else 'pdu' if 'T{pdu.pdu}' == 'V{node}' else 'server'  }}
    device_info:
      arch: {{ 'T{nodetype.arch}' }}
      supportedarchs: {{ 'T{nodetype.supportedarchs}' }}
      disksize: {{ 'T{hwinv.disksize}' }}
      memory: {{ 'T{hwinv.memory}' }}
      cputype: {{ 'T{hwinv.cputype}' }}
      cpucount: {{ 'T{hwinv.cpucount}' }}
      mtm: {{ 'T{vpd.mtm}' }}
      uuid: {{ 'T{vpd.uuid}' }}
      switchtype: {{ 'T{switches.switchtype}' if 'V{device_type}' == 'switch' else None }}
      pdutype:  {{ 'T{pdu.machinetype}' if 'V{device_type}' == 'pdu' else None }}
      outlets: {{ 'T{pdu.outlet}' if 'V{device_type}' == 'pdu' else None }}
      model: {{ 'T{pdu.modelnum}' if 'V{device_type}' == 'pdu' else None }}
      serial: {{ 'T{pdu.serialnum}' if 'V{device_type} == 'pdu' else 'T{vpd.serial}' if 'V{device_type} == 'node' else None}}
````
