### ISSUE TITLE
goconserver cannot be started on service node

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#4542]
There are two issue:
1, If goconserver is started already, makegocons will not generate the config file on node. 
Need some discussion here, maybe introduce an new option to force generate and reload service.

2, Even with the  config file generated by `makegocons`, `goconserver` cannot be started as the cert file is not installed on service node.

```
#cat /etc/goconserver/server.conf
global:
  host: c910f03c05k29
  ssl_key_file: /etc/xcat/cert/server-key.pem
  ssl_cert_file: /etc/xcat/cert/server-cert.pem
  ssl_ca_cert_file: /etc/xcat/cert/ca.pem
  logfile: /var/log/goconserver/server.log
api:
  port: 12429
console:
  port: 12430
```

```
# ls -l /etc/xcat/cert/
total 16
-rw-------. 1 root root 4296 Dec 11 04:50 ca.pem
-rw-------. 1 root root 5444 Dec 11 04:50 server-cred.pem
```

After copy the two missing file, goconserver could work as normal.
