### ISSUE TITLE
[Travis CI] use "ShellCheck" to validate the shell scripts in xCAT commits

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4610]
`ShellCheck` is a GPLv3 tool that gives warnings and suggestions for bash/sh shell scripts, we can leverage it to impose a strict check on the shell scripts in xCAT

From https://github.com/koalaman/shellcheck: 
The goals of ShellCheck are

* To point out and clarify typical beginner's syntax issues that cause a shell to give cryptic error messages.

* To point out and clarify typical intermediate level semantic problems that cause a shell to behave strangely and counter-intuitively.

* To point out subtle caveats, corner cases and pitfalls that may cause an advanced user's otherwise working script to fail under future circumstances.
Travis CI Setup

If you want to use ShellCheck in Travis CI, you can most easily install it via apt:
````
language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
````
