### ISSUE TITLE
[xcat-inventory] Failed to import "power_mgt_engine" for x86_64 server

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#5028]
The content planed to import:
```
x86_64_node:
    device_info:
      arch: x86_64
      .....
      netboot_engine:
        engine_type: xnba
      power_mgt_engine:
        engine_type: ipmi
```
Import result: ``Inventory import successfully!``
Check "nodehm" table:
```
# tabdump nodehm
#node,power,mgt,cons,termserver,termport,conserver,serialport,serialspeed,serialflow,getmac,cmdmapping,consoleondemand,consoleenabled,comments,disable
"ipmi_node",,"ipmi","ipmi",,,,"0","115200",,,,,,,
"openbmc_node",,"openbmc","openbmc",,,,,,,,,,,,
"x86_64_node",,"ipmi","ipmi",,,,"0","115200",,,,,,,
```
